'''All locations available to the prediction model.'''

from enum import Enum

class Location(str, Enum):
	'''Enum class containing all locations available to the prediction model.'''
	Albury = "Albury"
	BadgerysCreek = "BadgerysCreek"
	Cobar = "Cobar"
	CoffsHarbour = "CoffsHarbour"
	Moree = "Moree"
	Newcastle = "Newcastle"
	NorahHead = "NorahHead"
	NorfolkIsland = "NorfolkIsland"
	Penrith = "Penrith"
	Richmond = "Richmond"
	Sydney = "Sydney"
	SydneyAirport = "SydneyAirport"
	WaggaWagga = "WaggaWagga"
	Williamtown = "Williamtown"
	Wollongong = "Wollongong"
	Canberra = "Canberra"
	Tuggeranong = "Tuggeranong"
	MountGinini = "MountGinini"
	Ballarat = "Ballarat"
	Bendigo = "Bendigo"
	Sale = "Sale"
	MelbourneAirport = "MelbourneAirport"
	Melbourne = "Melbourne"
	Mildura = "Mildura"
	Nhil = "Nhil"
	Portland = "Portland"
	Watsonia = "Watsonia"
	Dartmoor = "Dartmoor"
	Brisbane = "Brisbane"
	Cairns = "Cairns"
	GoldCoast = "GoldCoast"
	Townsville = "Townsville"
	Adelaide = "Adelaide"
	MountGambier = "MountGambier"
	Nuriootpa = "Nuriootpa"
	Woomera = "Woomera"
	Albany = "Albany"
	Witchcliffe = "Witchcliffe"
	PearceRAAF = "PearceRAAF"
	PerthAirport = "PerthAirport"
	Perth = "Perth"
	SalmonGums = "SalmonGums"
	Walpole = "Walpole"
	Hobart = "Hobart"
	Launceston = "Launceston"
	AliceSprings = "AliceSprings"
	Darwin = "Darwin"
	Katherine = "Katherine"
	Uluru = "Uluru"
